"""initial_schema

Revision ID: f06f43a706f2
Revises: 
Create Date: 2026-09-11 17:07:32.122462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f06f43a706f2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('actor_user_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=80), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_tenant_id'), 'audit_logs', ['tenant_id'], unique=False)
    op.create_table('forecasts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('branch_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('p10', sa.Float(), nullable=False),
    sa.Column('p50', sa.Float(), nullable=False),
    sa.Column('p90', sa.Float(), nullable=False),
    sa.Column('model_version', sa.String(length=100), nullable=False),
    sa.Column('data_quality', sa.Float(), nullable=False),
    sa.Column('reasons_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'branch_id', 'product_id', 'business_date', 'model_version', name='uq_forecast_version')
    )
    op.create_index(op.f('ix_forecasts_branch_id'), 'forecasts', ['branch_id'], unique=False)
    op.create_index(op.f('ix_forecasts_business_date'), 'forecasts', ['business_date'], unique=False)
    op.create_index(op.f('ix_forecasts_product_id'), 'forecasts', ['product_id'], unique=False)
    op.create_index(op.f('ix_forecasts_tenant_id'), 'forecasts', ['tenant_id'], unique=False)
    op.create_table('inventory_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('branch_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('closing_qty', sa.Float(), nullable=False),
    sa.Column('data_flag', sa.String(length=30), nullable=False),
    sa.Column('idempotency_key', sa.String(length=100), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_inventory_snapshots_branch_id'), 'inventory_snapshots', ['branch_id'], unique=False)
    op.create_index(op.f('ix_inventory_snapshots_business_date'), 'inventory_snapshots', ['business_date'], unique=False)
    op.create_index(op.f('ix_inventory_snapshots_product_id'), 'inventory_snapshots', ['product_id'], unique=False)
    op.create_index(op.f('ix_inventory_snapshots_tenant_id'), 'inventory_snapshots', ['tenant_id'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('forecast_id', sa.String(length=36), nullable=False),
    sa.Column('branch_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('recommended_prep', sa.Float(), nullable=False),
    sa.Column('risk', sa.String(length=30), nullable=False),
    sa.Column('policy_version', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['forecast_id'], ['forecasts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_branch_id'), 'recommendations', ['branch_id'], unique=False)
    op.create_index(op.f('ix_recommendations_business_date'), 'recommendations', ['business_date'], unique=False)
    op.create_index(op.f('ix_recommendations_forecast_id'), 'recommendations', ['forecast_id'], unique=False)
    op.create_index(op.f('ix_recommendations_product_id'), 'recommendations', ['product_id'], unique=False)
    op.create_index(op.f('ix_recommendations_tenant_id'), 'recommendations', ['tenant_id'], unique=False)
    op.create_table('overrides',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('recommendation_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('old_value', sa.Float(), nullable=False),
    sa.Column('new_value', sa.Float(), nullable=False),
    sa.Column('reason_code', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_overrides_recommendation_id'), 'overrides', ['recommendation_id'], unique=False)
    op.create_index(op.f('ix_overrides_tenant_id'), 'overrides', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_overrides_tenant_id'), table_name='overrides')
    op.drop_index(op.f('ix_overrides_recommendation_id'), table_name='overrides')
    op.drop_table('overrides')
    op.drop_index(op.f('ix_recommendations_tenant_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_product_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_forecast_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_business_date'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_branch_id'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_inventory_snapshots_tenant_id'), table_name='inventory_snapshots')
    op.drop_index(op.f('ix_inventory_snapshots_product_id'), table_name='inventory_snapshots')
    op.drop_index(op.f('ix_inventory_snapshots_business_date'), table_name='inventory_snapshots')
    op.drop_index(op.f('ix_inventory_snapshots_branch_id'), table_name='inventory_snapshots')
    op.drop_table('inventory_snapshots')
    op.drop_index(op.f('ix_forecasts_tenant_id'), table_name='forecasts')
    op.drop_index(op.f('ix_forecasts_product_id'), table_name='forecasts')
    op.drop_index(op.f('ix_forecasts_business_date'), table_name='forecasts')
    op.drop_index(op.f('ix_forecasts_branch_id'), table_name='forecasts')
    op.drop_table('forecasts')
    op.drop_index(op.f('ix_audit_logs_tenant_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
